### ISSUE TITLE
这里报错，源文件没有更改过。

### ISSUE THREAD

**Issue by ljq29** [wblgers/py_speech_seg#4]
Traceback (most recent call last):
  File "c:\Users\jiaqi.Li\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\jiaqi.Li\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 410, in main
    run()
  File "c:\Users\jiaqi.Li\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\moviesub_proj\py_speech_seg-master\multi_detect.py", line 11, in <module>
    cluster_method='bic')
  File "e:\moviesub_proj\py_speech_seg-master\speech_segmentation.py", line 122, in multi_segmentation
    y, sr = librosa.load(file, sr=sr)
  File "D:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "D:\ProgramData\Anaconda3\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\ProgramData\Anaconda3\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\moviesub_proj\\duihua_sample.wav'

**Comment by wblgers** [comment]
You should check that the file duihua_sample.wav is located in the right place.

**Comment by ljq29** [comment]
The file duihua_sample.wav is in the right place.

**Comment by wblgers** [comment]
> The file duihua_sample.wav is in the right place.

你看到这个错误了吗？
FileNotFoundError: [Errno 2] No such file or directory: 'E:\moviesub_proj\duihua_sample.wav'
它提示的就是找不到这个路径下的文件。

**Comment by ljq29** [comment]
Yes, I know the exact meaning of errors.
Although the file in the right place, it happens again.
